config/routes.rb
Rails.application.routes.draw do
  resources :liked_teams
  resources :games, only: [:index]

  root 'games#index'

  # Save game on like
  post 'standings/like', to: 'standings#like', as: 'like_standings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :team_stats
end

app/models/team_stat.rb
class TeamStat < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'uri'
require 'net/http'
require 'openssl'


class GamesController < ApplicationController
  """
    # Get the standings from the API
    # https://rapidapi.com/api-sports/api/api-football
    # Show case the data in the view as stangins
  """
    def index
      url = URI("https://premier-league-standings1.p.rapidapi.com/")

      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
  
      request = Net::HTTP::Get.new(url)

      # this api key is for testing purposes only will be removed after the project is done
      request["X-RapidAPI-Key"] = 'e32ac445e6msh34a1aa4e3b8ab24p1ad76cjsn528d9475314b'
      request["X-RapidAPI-Host"] = 'premier-league-standings1.p.rapidapi.com'
      
      response = http.request(request)
      puts "-------- response ----------"
      puts response.read_body
      @standings = JSON.parse(response.read_body)
    end
  
end

app/controllers/liked_teams_controller.rb
class LikedTeamsController < ApplicationController
  before_action :set_liked_team, only: %i[ show edit update destroy ]

  # GET /liked_teams or /liked_teams.json
  def index
    @liked_teams = LikedTeam.all
  end

  # GET /liked_teams/1 or /liked_teams/1.json
  def show
  end

  # GET /liked_teams/new
  def new
    @liked_team = LikedTeam.new
  end

  # GET /liked_teams/1/edit
  def edit
  end

  # POST /liked_teams or /liked_teams.json
  def create
    @liked_team = LikedTeam.new(liked_team_params)

    respond_to do |format|
      if @liked_team.save
        format.html { redirect_to liked_team_url(@liked_team), notice: "Liked team was successfully created." }
        format.json { render :show, status: :created, location: @liked_team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @liked_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liked_teams/1 or /liked_teams/1.json
  def update
    respond_to do |format|
      if @liked_team.update(liked_team_params)
        format.html { redirect_to liked_team_url(@liked_team), notice: "Liked team was successfully updated." }
        format.json { render :show, status: :ok, location: @liked_team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @liked_team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liked_teams/1 or /liked_teams/1.json
  def destroy
    @liked_team.destroy

    respond_to do |format|
      format.html { redirect_to liked_teams_url, notice: "Liked team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liked_team
      @liked_team = LikedTeam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def liked_team_params
      params.fetch(:liked_team, {})
    end
end

app/controllers/standings_controller.rb
# save liked game
def Like
    # load params from request into variables
    team_rank = params[:team_rank]
    team_name = params[:team_name]
    games_played = params[:games_played]
    wins = params[:wins]
    losses = params[:losses]
    ties = params[:ties]    

    # Check if team with the same name already exists
    if TeamStats.exists?(name: team_name)
        puts "Team #{team_name} already exists"
        return
    end
    
    # Create new team stats from params--variables
    team_stats = TeamStats.new(rank: team_rank, name: team_name, games_played: games_played, wins: wins, losses: losses, ties: ties)
    puts "-------- team_stats saved --------"
    team_stats.save
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/liked_teams_helper.rb
module LikedTeamsHelper
end

app/helpers/live_online_games_helper.rb
module LiveOnlineGamesHelper
end

app/views/games/index.html.erb
<div class="container" align="center">
<h1>English Premier League Standings</h1>
<h2>Welcome To MyGame.com Team Yako Updates Zako</h2>
<hr>
<h3>Season 2023</h3>
<img src="https://thesportslite.com/wp-content/uploads/2021/09/English-Premier-League-.jpeg" alt="EPL Logo">
<hr>
<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Team</th>
      <th>Games Played</th>
      <th>Wins</th>
      <th>Losses</th>
      <th>Ties</th>
      <th>Like team for update</th>
    </tr>
  </thead>
  <tbody>
    <% @standings.each do |team| %>
      <tr>
        <td><%= team["stats"]["rank"] %></td>
        <td><%= team["team"]["name"] %></td>
        <td><%= team["stats"]["gamesPlayed"] %></td>
        <td><%= team["stats"]["wins"] %></td>
        <td><%= team["stats"]["losses"] %></td>
        <td><%= team["stats"]["ties"] %></td>
        <td><%= button_to '👍', like_standings_path, method: :post, params: { 
          team_rank: team["stats"]["rank"],team_name:team["team"]["name"], 
          games_played: team["stats"]["gamesPlayed"], wins: team["stats"]["wins"],
          losses: team["stats"]["losses"], ties: team["stats"]["ties"]
        } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballMatchesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet", href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/liked_teams/_form.html.erb
<%= form_with(model: liked_team) do |form| %>
  <% if liked_team.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(liked_team.errors.count, "error") %> prohibited this liked_team from being saved:</h2>

      <ul>
        <% liked_team.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/liked_teams/_liked_team.html.erb
<div id="<%= dom_id liked_team %>">
</div>

app/views/liked_teams/edit.html.erb
<h1>Editing liked team</h1>

<%= render "form", liked_team: @liked_team %>

<br>

<div>
  <%= link_to "Show this liked team", @liked_team %> |
  <%= link_to "Back to liked teams", liked_teams_path %>
</div>

app/views/liked_teams/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Liked teams</h1>

<div id="liked_teams">
  <% @liked_teams.each do |liked_team| %>
    <%= render liked_team %>
    <p>
      <%= link_to "Show this liked team", liked_team %>
    </p>
  <% end %>
</div>

<%= link_to "New liked team", new_liked_team_path %>

app/views/liked_teams/new.html.erb
<h1>New liked team</h1>

<%= render "form", liked_team: @liked_team %>

<br>

<div>
  <%= link_to "Back to liked teams", liked_teams_path %>
</div>

app/views/liked_teams/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @liked_team %>

<div>
  <%= link_to "Edit this liked team", edit_liked_team_path(@liked_team) %> |
  <%= link_to "Back to liked teams", liked_teams_path %>

  <%= button_to "Destroy this liked team", @liked_team, method: :delete %>
</div>